export const audioFiles = [
  {
    id: 'audio_001',
    title: 'Morning Garden Recording',
    description: 'Field recording captured at dawn with birds and wind sounds',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_001.mp3',
    duration: 245,
    category: 'field-recordings',
    hotspot: { x: 10, y: 15 },
    artist: 'Jane Doe',
    date: '2025-03-15',
    downloadable: true
  },
  {
    id: 'audio_002',
    title: 'Afternoon Garden Walk',
    description: 'Peaceful walk through the garden in afternoon light',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_002.mp3',
    duration: 320,
    category: 'field-recordings',
    hotspot: { x: 25, y: 30 },
    artist: 'John Smith',
    date: '2025-03-16',
    downloadable: true
  },
  {
    id: 'audio_003',
    title: 'Garden Rain Sounds',
    description: 'Ambient recording of rainfall in the garden',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_003.mp3',
    duration: 180,
    category: 'ambience',
    hotspot: { x: 45, y: 20 },
    artist: 'Nature Sounds',
    date: '2025-03-17',
    downloadable: true
  },
  {
    id: 'audio_004',
    title: 'Birdsong at Dusk',
    description: 'Evening birdsong with sunset ambience',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_004.mp3',
    duration: 290,
    category: 'field-recordings',
    hotspot: { x: 60, y: 40 },
    artist: 'Emma Wilson',
    date: '2025-03-18',
    downloadable: true
  },
  {
    id: 'audio_005',
    title: 'Garden Interview - Part 1',
    description: 'Conversation about sustainable gardening practices',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_005.mp3',
    duration: 420,
    category: 'interviews',
    hotspot: { x: 75, y: 50 },
    artist: 'Alex Chen',
    date: '2025-03-19',
    downloadable: true
  },
  {
    id: 'audio_006',
    title: 'Garden Interview - Part 2',
    description: 'Continuation of sustainable gardening discussion',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_006.mp3',
    duration: 380,
    category: 'interviews',
    hotspot: { x: 85, y: 55 },
    artist: 'Alex Chen',
    date: '2025-03-19',
    downloadable: true
  },
  {
    id: 'audio_007',
    title: 'Insect Chorus',
    description: 'Symphony of insects in the evening garden',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_007.mp3',
    duration: 240,
    category: 'field-recordings',
    hotspot: { x: 30, y: 70 },
    artist: 'Nature Sounds',
    date: '2025-03-20',
    downloadable: true
  },
  {
    id: 'audio_008',
    title: 'Garden Meditation',
    description: 'Guided meditation in the peaceful garden setting',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_008.mp3',
    duration: 480,
    category: 'meditation',
    hotspot: { x: 50, y: 75 },
    artist: 'Sarah Miller',
    date: '2025-03-21',
    downloadable: true
  },
  {
    id: 'audio_009',
    title: 'Water Features Recording',
    description: 'Soothing sounds of fountains and water flow',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_009.mp3',
    duration: 300,
    category: 'ambience',
    hotspot: { x: 15, y: 45 },
    artist: 'Ambient Garden',
    date: '2025-03-22',
    downloadable: true
  },
  {
    id: 'audio_010',
    title: 'Spring Garden Walk',
    description: 'Journey through the garden in spring bloom',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_010.mp3',
    duration: 350,
    category: 'field-recordings',
    hotspot: { x: 70, y: 25 },
    artist: 'Michael Brown',
    date: '2025-03-23',
    downloadable: true
  },
  {
    id: 'audio_011',
    title: 'Garden History - Episode 1',
    description: 'Historical overview of the garden through decades',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_011.mp3',
    duration: 450,
    category: 'documentary',
    hotspot: { x: 20, y: 60 },
    artist: 'Dr. Historical',
    date: '2025-03-24',
    downloadable: true
  },
  {
    id: 'audio_012',
    title: 'Garden History - Episode 2',
    description: 'Modern era and future plans for the garden',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_012.mp3',
    duration: 420,
    category: 'documentary',
    hotspot: { x: 35, y: 65 },
    artist: 'Dr. Historical',
    date: '2025-03-24',
    downloadable: true
  },
  {
    id: 'audio_013',
    title: 'Nocturnal Garden Sounds',
    description: 'Night-time recordings of the garden ecosystem',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_013.mp3',
    duration: 280,
    category: 'field-recordings',
    hotspot: { x: 55, y: 80 },
    artist: 'Night Listener',
    date: '2025-03-25',
    downloadable: true
  },
  {
    id: 'audio_014',
    title: 'Garden Composition #1',
    description: 'Original musical piece inspired by garden sounds',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_014.mp3',
    duration: 360,
    category: 'music',
    hotspot: { x: 80, y: 35 },
    artist: 'Composer Luna',
    date: '2025-03-26',
    downloadable: true
  },
  {
    id: 'audio_015',
    title: 'Garden Composition #2',
    description: 'Second musical composition in the garden series',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_015.mp3',
    duration: 420,
    category: 'music',
    hotspot: { x: 90, y: 70 },
    artist: 'Composer Luna',
    date: '2025-03-26',
    downloadable: true
  },
  {
    id: 'audio_016',
    title: 'Garden Tour Guide',
    description: 'Complete guided tour with interesting facts and stories',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_016.mp3',
    duration: 600,
    category: 'tour',
    hotspot: { x: 40, y: 50 },
    artist: 'Guide Maria',
    date: '2025-03-27',
    downloadable: true
  },
  {
    id: 'audio_017',
    title: 'Seasonal Changes Recording',
    description: 'Exploration of how the garden changes through seasons',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_017.mp3',
    duration: 480,
    category: 'documentary',
    hotspot: { x: 65, y: 15 },
    artist: 'Seasonal Observer',
    date: '2025-03-28',
    downloadable: true
  },
  {
    id: 'audio_018',
    title: 'Garden Biodiversity Study',
    description: 'Audio essay on the diverse species in the garden',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_018.mp3',
    duration: 390,
    category: 'educational',
    hotspot: { x: 25, y: 85 },
    artist: 'Dr. Biodiversity',
    date: '2025-03-29',
    downloadable: true
  },
  {
    id: 'audio_019',
    title: 'Garden Dreams - Final Piece',
    description: 'Reflective audio piece about the garden experience',
    cloudinaryUrl: 'https://res.cloudinary.com/YOUR_CLOUD/video/upload/v1/audio_019.mp3',
    duration: 350,
    category: 'reflective',
    hotspot: { x: 50, y: 90 },
    artist: 'Final Voice',
    date: '2025-03-30',
    downloadable: true
  }
];
